tf1_converter:
  input: input
  output: output
  icon_path: c:\program files\gpx2kml\icon\tf_ge\
  start_path: c:\program files\gpx2kml\test
  end_path: c:\program files\gpx2kml\test
  icons: { Custom 0: { icon: 01.png, meaning: Search Start, name: icon_name_1 },
           Custom 1: { icon: 02.png, meaning: Search Stop, name: icon_name_2 },
           Custom 2: { icon: 03.png, meaning: Victim Detected, name: icon_name_3},
           Custom 3: { icon: 04.png, meaning: Victim Confirmed, name: icon_name_4},
           Custom 4: { icon: 05.png, meaning: Meaning 5, name: icon_name_5},
           Custom 5: { icon: 06.png, meaning: Meaning 6, name: icon_name_6},
           Custom 6: { icon: 07.png, meaning: Meaning 7, name: icon_name_7},
           Custom 7: { icon: 08.png, meaning: Meaning 8, name: icon_name_8},
           Custom 8: { icon: 09.png, meaning: Meaning 9, name: icon_name_9},
           Custom 9: { icon: 10.png, meaning: Meaning 10, name: icon_name_10},
           Custom 10: { icon: 11.png, meaning: Collection Point , name: icon_name_11},
           Custom 11: { icon: 12.png, meaning: Meaning 12, name: icon_name_12},
           Custom 12: { icon: 13.png, meaning: Command Post, name: icon_name_13 },
           Custom 13: { icon: 14.png, meaning: Staging Area, name: icon_name_14 },
           Custom 14: { icon: 15.png, meaning: Criminal Activity, name: icon_name_15 },
           Custom 15: { icon: 16.png, meaning: Meaning 16, name: icon_name_16 },
           Custom 16: { icon: 17.png, meaning: Water Level, name: icon_name_17 },
           Custom 17: { icon: 18.png, meaning: Structure Damage / Safe, name: icon_name_18 },
           Custom 18: { icon: 19.png, meaning: Meaning 19, name: icon_name_19 },
           Custom 19: { icon: 20.png, meaning: Structure Not Safe, name: icon_name_20 },
           Custom 20: { icon: 21.png, meaning: Extra 21, name: icon_name_21 },
           Custom 21: { icon: 22.png, meaning: Extra 22, name: icon_name_22 },
           Custom 22: { icon: 23.png, meaning: Extra 23, name: icon_name_23 },
           Residence: { icon: default.png, meaning: Default, name: icon_name_24 } }
  colors: { DarkRed: f0000080,
            Yellow: f000ffff,
            Blue: f0ff0000 }
