tf1_converter:
  input: input
  output: output
  icon_path: c:\program files\gpx2kml\icon\tf_ge\
  start_path: c:\program files\gpx2kml\test
  end_path: c:\program files\gpx2kml\test
  icons: { Custom 0: { icon: 01.png, meaning: Search Start },
           Custom 1: { icon: 02.png, meaning: Search Stop},
           Custom 2: { icon: 03.png, meaning: Victim Detected},
           Custom 3: { icon: 04.png, meaning: Victim Confirmed},
           Custom 4: { icon: 05.png, meaning: Meaning 5},
           Custom 5: { icon: 06.png, meaning: Meaning 6},
           Custom 6: { icon: 07.png, meaning: Meaning 7},
           Custom 7: { icon: 08.png, meaning: Meaning 8},
           Custom 8: { icon: 09.png, meaning: Meaning 9},
           Custom 9: { icon: 10.png, meaning: Meaning 10},
           Custom 10: { icon: 11.png, meaning: Collection Point },
           Custom 11: { icon: 12.png, meaning: Meaning 12},
           Custom 12: { icon: 13.png, meaning: Command Post },
           Custom 13: { icon: 14.png, meaning: Staging Area},
           Custom 14: { icon: 15.png, meaning: Criminal Activity },
           Custom 15: { icon: 16.png, meaning: Meaning 16},
           Custom 16: { icon: 17.png, meaning: Water Level},
           Custom 17: { icon: 18.png, meaning: Structure Damage / Safe },
           Custom 18: { icon: 19.png, meaning: Meaning 19},
           Custom 19: { icon: 20.png, meaning: Structure Not Safe },
           Custom 20: { icon: 21.png, meaning: Extra 21 },
           Custom 21: { icon: 22.png, meaning: Extra 22 },
           Custom 22: { icon: 23.png, meaning: Extra 23},
           Residence: { icon: default.png, meaning: Default } }
  colors: { DarkRed: f0000080,
            Yellow: f000ffff,
            Blue: f0ff0000 }
