tf1_converter:
  input: c:\Documents and Settings\FEMA\TF1Converter\Input
  output: c:\Documents and Settings\FEMA\TF1Converter\Output
  icon_path: c:\Program Files\GPX2KML\icon\tf_ge\
  start_path: c:\Program Files\GPX2KML\test
  end_path: c:\Program Files\GPX2KML\test
  icons: { Custom 0: { icon: 01.png, meaning: Search Start, name: name1 },
           Custom 1: { icon: 02.png, meaning: Search Stop, name: name2},
           Custom 2: { icon: 03.png, meaning: Victim Detected, name: name3},
         Custom 3: { icon: 04.png, meaning: Victim Confirmed, name: name4},
	       Custom 4: { icon: 05.png, meaning: Meaning 5, name: name5},
	       Custom 5: { icon: 06.png, meaning: Meaning 6, name: name6},
	       Custom 6: { icon: 07.png, meaning: Meaning 7, name: name7},
	       Custom 7: { icon: 08.png, meaning: Meaning 8, name: name8},
	       Custom 8: { icon: 09.png, meaning: Meaning 9, name: name9},
	       Custom 9: { icon: 10.png, meaning: Meaning 10, name: name10},
	       Custom 10: { icon: 11.png, meaning: Collection Point, name: name11 },
	       Custom 11: { icon: 12.png, meaning: Meaning 12, name: name12},
	       Custom 12: { icon: 13.png, meaning: Command Post, name: name13 },
	       Custom 13: { icon: 14.png, meaning: Staging Area, name: name14},
	       Custom 14: { icon: 15.png, meaning: Criminal Activity, name: name15 },
	       Custom 15: { icon: 16.png, meaning: Meaning 16, name: name16},
	       Custom 16: { icon: 17.png, meaning: Water Level, name: name17},
	       Custom 17: { icon: 18.png, meaning: Structure Damage / Safe, name: name18 },
	       Custom 18: { icon: 19.png, meaning: Meaning 19, name: name19},
	       Custom 19: { icon: 20.png, meaning: Structure Not Safe, name: name20 },
	       Custom 20: { icon: 21.png, meaning: Extra 21, name: name21 },
	       Custom 21: { icon: 22.png, meaning: Extra 22, name: name22 },
	       Custom 22: { icon: 23.png, meaning: Extra 23, name: name23},
	       Residence: { icon: default.png, meaning: Default, name: name24 } }
  colors: { DarkRed: f0000080,
            Yellow: f000ffff }
